# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161031_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'DownVote')], verbose_name='value'),
        ),
    ]
