# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161122_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpost',
            name='imgurl',
            field=models.URLField(default='/static/images/a.png', verbose_name='imgurl'),
        ),
    ]
