# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_auto_20161121_1712'),
        ('posts', '0003_post_expires_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('time', models.DateTimeField(verbose_name='created_on')),
                ('venue', models.CharField(max_length=50, verbose_name='venue')),
                ('description', models.TextField(verbose_name='description')),
                ('posted_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subreddits.Subreddit')),
            ],
            bases=('posts.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 14, 27, 26, 837685, tzinfo=utc), verbose_name='expires_on'),
        ),
    ]
