# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161122_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 14, 59, 7, 593858, tzinfo=utc), verbose_name='expires_on'),
        ),
    ]
