# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20161122_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 15, 32, 49, 398782, tzinfo=utc), verbose_name='expires_on'),
        ),
    ]
