# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20161122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 17, 24, 18, 396824, tzinfo=utc), verbose_name='expires_on'),
        ),
    ]
