# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20161122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(verbose_name='expires_on'),
        ),
    ]
