# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redditer',
            fields=[
                ('joined_on', models.DateTimeField(auto_now_add=True, verbose_name='joined_on')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
