# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redditer', models.ManyToManyField(to='users.Redditer')),
                ('subreddit', models.ManyToManyField(to='subreddits.Subreddit')),
            ],
        ),
    ]
