# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditer',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='joined_on'),
        ),
    ]
