# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import subreddits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[subreddits.models.validate_nospace], verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
