# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import subreddits.models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='id',
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[subreddits.models.validate_nospace], verbose_name='title'),
        ),
    ]
